#!/usr/bin/python

import csv
import errno
import sys
import os
import re


if len(sys.argv) < 2:
    print("Usage: %s file1.csv file2.csv ..." % sys.argv[0])
    sys.exit(1)

data = []
for source in sys.argv[1:]:
    basename = os.path.splitext(os.path.basename(source))[0]
    file = open(source)
    reader = csv.reader(file, delimiter=',', quotechar='"')
    data.append({"basename": basename, "data": [row for row in reader][1:]})

languages = {
    "de": 0,
    "fr": 1,
    "it": 2,
    "en": 3
}

chapre = re.compile(r"^#\s+(.*)$")
sectre = re.compile(r"^##\s+(.*)$")

for lang in languages:
    outdir = os.path.join("..", lang)
    try:
        os.makedirs(outdir)
    except OSError as e:
        if e.errno != errno.EEXIST:
            raise
    summaryfile = open(os.path.join(outdir, "SUMMARY.md"), "w")
    for document in data:
        basename = document["basename"]
        i = 0
        outfile = open(os.path.join(outdir, basename + ".md"), "w")
        outfile.write("<!-- WARNING: This file is autogenerated by csv2md.py -->\n")
        for row in document["data"]:
            cell = row[languages[lang]]
            cellrows = cell.split("\n")
            chapmatch = chapre.match(cellrows[0])
            sectmatch = sectre.match(cellrows[0])
            if chapmatch:
                summaryfile.write("* [{title}]({basename}.md)\n".format(title=chapmatch.group(1), basename=basename))
            if sectmatch:
                cellrows[0] = '## <a name="sec%d"></a>%s' % (i, sectmatch.group(1))
                summaryfile.write("  - [{title}]({basename}.md#{anchor})\n".format(title=sectmatch.group(1), basename=basename, anchor="sec%d" % i))
                i += 1

            outfile.write("\n".join(cellrows))
            outfile.write("\n\n")
        outfile.close()
    with open(os.path.join(outdir, "SUMMARY_extra.md"), "r") as extrasummary:
        summaryfile.write(extrasummary.read())
    summaryfile.close()
